### ISSUE TITLE
Accept "alternative" notations

### ISSUE THREAD

**Issue by fabm22** [AaronLayton/bem-highlighter#2]
There is a few variations in the BEM notation (yandex original one, SUIT css with more camelCase approach) etc.

Would be nice, I guess, to accept those. Some projects ([html-inspector](https://github.com/philipwalton/html-inspector) for example) use some regexp to distinguish them, so it would be easy to leverage the approach.

**Comment by AaronLayton** [comment]
@fabm22 sounds good to me. Could you give me a few examples here in comments of the different ones to implement

**Comment by fabm22** [comment]
Hi, thanks for answer. 

Here's for example the code from HTML Inspector used to distinguish between the 3 most (it seems) known variations.

https://github.com/philipwalton/html-inspector/blob/master/src/rules/convention/bem-conventions.js

**Comment by AaronLayton** [comment]
Sorry it took so long - I had it on a Develop branch for a while. Try the latest version if you still need this
